language: python
cache: pip

python:
- 2.7

before_install:

install:
- pip install -r requirements.txt
- pip install -e .
- pip install coveralls

before_script:
- cd vosi

script:
- coverage run runtests.py

after_success:
- coveralls