# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vosi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voresource_capability',
            name='appname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
